Do not manually check for ascii range
Clippy emits:

 error: manual check for common ascii range

As suggested, use `is_ascii_*` methods instead of checking for ascii
rang manually.